services:
  bachelor-neo4j:
    image: neo4j:5.20.0
    environment:
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_server_memory_pagecache_size=5G
      - NEO4J_server_memory_heap_initial__size=10G
      - NEO4J_server_memory_heap_max__size=10G
      - NEO4J_AUTH=neo4j/theBestNeo4JPassword4ever

    ports:
      - "7474:7474"
      - "7687:7687"